config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root 'main#index'

  # Sign Up
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  # Password
  get 'password', to: 'passwords#edit'
  patch 'password', to: 'passwords#update'

  # Sign In
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Password Reset
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  # Twitter
  get '/auth/twitter/callback', to: 'omniauth_callbacks#twitter'

  # About
  get 'about', to: 'about#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  validates :password, :password_confirmation, presence: true, length: { minimum: 6 }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by_id(session[:user_id])
    end
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: "You must be sign to do that." if Current.user.nil?
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index; end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def twitter
    
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      #Send email
      PasswordMailer.with(user: @user).reset.deliver_later
    end
    redirect_to root_path, notice: "If an account with that email was found, we have sent a link to reset your password to your email"
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to root_path, notice: "Token Expired, Please try again!"
  end

  def update
    @user = User.find_signed!(params[:token], purpose: "password_reset")

    if @user.update(password_params)
      redirect_to sign_in_path, notice: "Your password was reseted. Please sign in"
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!, only: [:edit, :update]

  def edit
  end

  def update
    if Current.user.authenticate(password_params[:old_password]) && Current.user.update({ password: password_params[:password], password_confirmation: password_params[:password_confirmation] })
      redirect_to root_path, notice: "Password Updated"
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation, :old_password)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Succesfully created account"
    else
      flash[:alert] = "Something Was Wrong"
      render :new
    end

  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])&.authenticate(params[:password])

    if @user
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully Logged In"
    else
      flash[:alert] = "Your Credentials Could Not Be Validated"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged Out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>
  About Page
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScheduleTweets</title>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <%= csrf_meta_tags %> <%= csp_meta_tag %>

  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
    crossorigin="anonymous"
    />
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"
  ></script>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render partial: 'shared/navbar' %>
<div class="container">
  <%= render partial: 'shared/flash' %>
  <%= yield %>
</div>
</body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center my-3">
  <h1>Welcome to Scheduled Tweets</h1>
</div>

<%= button_to "Connect Twitter", "/auth/twitter", method: :post, class: "btn btn-primary" %>

app/views/password_resets/edit.html.erb
<h1 class="my-3">Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
  <%= render partial: "shared/user_errors" %>

  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.submit "Reset password", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1 class="my-3">Forgot your password?</h1>

<%= form_with url: password_reset_path do |form| %>
  <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control", example: "steve@example.com" %>
  </div>
  <div class="mb-3">
    <%= form.submit "Send Email", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
      <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning mt-4">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
  <div class="container-fluid">
    <%= link_to 'ScheduledTweets', root_path, class: 'navbar-brand' %>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
        <%= link_to 'About', about_path, class: 'nav-link' %>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item dropdown ms-2">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= Current.user.email %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li>
                <%= link_to "Edit Password", password_path, class: 'dropdown-item' %>
              </li>
              <li>
                <%= button_to "Logout", logout_path, method: :delete, class: 'dropdown-item' %>
              </li>
            </ul>
          </li>
        <% else %>
          <%= link_to "Sign In", sign_in_path, class: 'nav-link' %>
          </ul>
        <% end %>
        </div>
  </div>
</nav>

app/views/shared/_user_errors.html.erb
<% if @user.errors.any? %>
  <ul class="list-group mb-3">
    <% @user.errors.full_messages.each do |m| %>
      <li class="list-group-item list-group-item-danger">
        <%= m %>
      </li>
    <% end %>
  </ul>
<% end %>